name: RanbooPower
version: 1.1.0
main: com.papajittan.ranboopower.Main
api-version: 1.18
author: Papajittan
commands:
  ranboo:
    description: Manage the player Ranboo power!
    usage: /ranboo <remove or add> <playername>
